# k8s/istio/wasm-filter.yaml
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: authz-cache-filter
  namespace: zta-research
spec:
  selector:
    matchLabels:
      app: productcatalogservice
  url: file:///etc/wasm/authz-cache.wasm
  phase: AUTHZ
  pluginConfig:
    pdp_endpoint: "http://opa-service:8181/v1/data/authz/allow"
