// Manually created stub to match cache.proto definitions.
// In production, regenerate with: protoc --go_out=. --go-grpc_out=. proto/cache.proto
package proto

import (
	"context"

	"google.golang.org/grpc"
)

// ─── Messages ───

type TokenPayload struct {
	TokenJson string
	Signature string
}

type RevocationRequest struct {
	SourceIdentity string
	TargetIdentity string
	OldNonce       string
}

type RevocationEvent struct {
	SourceIdentity string
	TargetIdentity string
	NewNonce       string
	Timestamp      int64
}

type SubscribeRequest struct {
	SidecarId string
}

type SubscriptionRequest = SubscribeRequest // alias for backward compat

type Ack struct {
	Success bool
	Message string
}

// ─── Server Interface ───

type CacheDistributorServer interface {
	PushToken(context.Context, *TokenPayload) (*Ack, error)
	RevokeToken(context.Context, *RevocationRequest) (*Ack, error)
	StreamRevocations(*SubscribeRequest, CacheDistributor_StreamRevocationsServer) error
}

// Alias for backward compat
type CacheDistributionServer = CacheDistributorServer

type CacheDistributor_StreamRevocationsServer interface {
	Send(*RevocationEvent) error
	Context() context.Context
	grpc.ServerStream
}

// Alias for backward compat
type CacheDistribution_SubscribeRevocationsServer = CacheDistributor_StreamRevocationsServer

// ─── Unimplemented Server ───

type UnimplementedCacheDistributorServer struct{}

func (UnimplementedCacheDistributorServer) PushToken(context.Context, *TokenPayload) (*Ack, error) {
	return &Ack{Success: false, Message: "not implemented"}, nil
}

func (UnimplementedCacheDistributorServer) RevokeToken(context.Context, *RevocationRequest) (*Ack, error) {
	return &Ack{Success: false, Message: "not implemented"}, nil
}

func (UnimplementedCacheDistributorServer) StreamRevocations(*SubscribeRequest, CacheDistributor_StreamRevocationsServer) error {
	return nil
}

// Alias for backward compat
type UnimplementedCacheDistributionServer = UnimplementedCacheDistributorServer

// ─── Registration ───

func RegisterCacheDistributorServer(s *grpc.Server, srv CacheDistributorServer) {
	// Stub: in production this is auto-generated by protoc-gen-go-grpc
	_ = s
	_ = srv
}

// Alias for backward compat
func RegisterCacheDistributionServer(s *grpc.Server, srv CacheDistributionServer) {
	RegisterCacheDistributorServer(s, srv)
}
